# Generated by Django 5.0.6 on 2024-06-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(max_length=100, verbose_name='Tarea')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('prioridad', models.CharField(max_length=100, verbose_name='Prioridad')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Entrega')),
            ],
        ),
    ]
