# Generated by Django 5.0.6 on 2024-07-06 23:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Estado')),
                ('descripcion_estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id_prioridad', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Prioridad')),
                ('descripcion_prioridad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Usuario')),
                ('nombre_usuario', models.CharField(max_length=255, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='id',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='prioridad',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='tarea',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2024, 8, 5, 23, 32, 24, 762199, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='id_proyecto',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='ID Proyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='nombre_proyecto',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='id_estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestor.estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='id_prioridad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestor.prioridad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prioridad',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.usuario'),
        ),
        migrations.AddField(
            model_name='estado',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.usuario'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestor.usuario'),
            preserve_default=False,
        ),
    ]
