# Generated by Django 5.0.6 on 2024-07-31 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0004_alter_estado_id_usuario_alter_prioridad_id_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='responsable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2024, 8, 30, 2, 49, 37, 254908, tzinfo=datetime.timezone.utc)),
        ),
    ]
