# Generated by Django 5.0.6 on 2024-07-31 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0005_proyecto_responsable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2024, 8, 30, 3, 36, 17, 369667, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='responsable',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
    ]
