# Generated by Django 5.0.6 on 2024-08-06 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0008_alter_proyecto_fecha_vencimiento_grupoproyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2024, 9, 5, 6, 49, 8, 176329, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='GrupoProyecto',
        ),
    ]
