# Generated by Django 5.0.6 on 2024-08-08 04:16

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0009_alter_proyecto_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='porcentaje',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2024, 9, 7, 4, 16, 15, 909355, tzinfo=datetime.timezone.utc)),
        ),
    ]
