# Generated by Django 5.0.6 on 2024-08-08 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0010_proyecto_porcentaje_alter_proyecto_fecha_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='porcentaje',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2024, 9, 7, 4, 59, 40, 597216, tzinfo=datetime.timezone.utc)),
        ),
    ]
