# Generated by Django 5.0.6 on 2024-08-09 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0011_remove_proyecto_porcentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='porcentaje',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2024, 9, 8, 21, 52, 57, 159477, tzinfo=datetime.timezone.utc)),
        ),
    ]
